language: python
python:
  - "3.8"
services:
  docker
env:
  global:
    - IMAGE_NAME=$DOCKER_USERNAME/discord-randomizer
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m py_compile ./bot.py
  - pytest -s -v
  - docker build -t "$IMAGE_NAME:$TRAVIS_COMMIT" .

after_script:
  - docker images

deploy:
  provider: script
  script: bash scipts/docker_push.sh
  on:
    branch: dev