language: python
python:
  - "3.8"
services:
  docker
env:
  global:
    - IMAGE_NAME=echolyn/discord-randomizer
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m py_compile ./bot.py
  - pytest
  - docker build --pull -cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images