language: python
python:
  - "3.8"
addons:
  apt:
    packages:
    - docker-ce
    - pass
services:
  docker
env:
  global:
    - IMAGE_NAME="$DOCKER_REPO/discord-randomizer"

before_install:
  - bash scripts/set_password.sh
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m py_compile ./bot.py
  - pytest -s -v
  - docker build -t "$IMAGE_NAME:dev" -t "$IMAGE_NAME:$TRAVIS_COMMIT" .

after_script:
  - docker images
  - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- "${IMAGE_NAME}:dev"

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: dev